FROM almalinux:9
CMD [ "google" ]
ENTRYPOINT [ "ping" ]
# used to run the commands
# CMD  and  Entry point both are used to  run the commands. But CMD can overriden but not entry point.
# For better practice CMD can provide  the ARGs to entrypoint. So you  can mention default args through CMD and override at run time.