FROM almalinux:9
RUN dnf install nginx -y
#run instructions run at build image  cmd run at conatiner creation
CMD [ "nginx", "-g", "daemon off;" ]
LABEL course="devops" \
    tariner="Siva kumar" \
    duration="120hrs"

